[package]
name = "untypedx"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "utx"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
clap = { version = "3", features = ["derive"] }
